name: syntax_highlight_light 
resolution: workspace
description: A simplified version of syntax_highlight but in pure dart so as to be useful outside of Flutter (e.g. jaspr) 
version: 0.0.1

environment:
  sdk: ">=3.6.0 <4.0.0"

# Add regular dependencies here.
dependencies:
  collection: any
  characters: any
  string_scanner: any

dev_dependencies:
  lints: any
  test: any
