name: lcov_format
resolution: workspace
description: A renderer for LCOV data produced by dart/flutter into some useful outputs.
repository: https://github.com/jtmcdole/lcov_format
version: 0.0.1

screenshots:
  - description: LCOV html format
    path: assets/screenshot_html.png
  - description: LCOV ansi format
    path: assets/screenshot_ansi.png

environment:
  sdk: ">=3.6.0 <4.0.0"

executables:
  lcov_format:

# Add regular dependencies here.
dependencies:
  ansicolor: ^2.0.3
  archive: ^4.0.4
  args: ^2.7.0
  crypto: ^3.0.6
  path: ^1.9.1
  syntax_highlight_lite: ^0.0.1

dev_dependencies:
  lints: ^5.1.1
