name: lcov_web
resolution: workspace
description: The client application for rendering `lcov_format` in a browser.
repository: https://github.com/jtmcdole/lcov_format
version: 0.0.1
publish_to: none

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  archive: ^4.0.4
  jaspr: ^0.18.0
  lcov_format: ^0.0.1
  logging: ^1.3.0
  path: ^1.9.1
  syntax_highlight_lite: ^0.0.1
  web: ^1.1.0

dev_dependencies:
  build_runner: ^2.4.15
  jaspr_builder: ^0.18.0
  jaspr_lints: ^0.3.1

jaspr:
  mode: client
